# Generated by Django 5.0.6 on 2024-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pix',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
