# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_profile_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pix",
            field=models.ImageField(upload_to="profile_pics/"),
        ),
    ]
