# Generated by Django 5.0.6 on 2024-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-id"]},
        ),
    ]
